'use strict';

const SAFETY = Object.freeze({
  actions_allowed: false,
  can_place_orders: false,
  live_trading_enabled: false,
  paper_only: true,
  replay_mode: true,
});

const MARKET_LABELS = Object.freeze({
  crypto: 'Krypto',
  stocks: 'Aktier',
  index: 'Index',
  etf: 'ETF',
  all: 'Alla',
});

function strategy({
  id,
  name,
  explanation,
  description_sv,
  simple_explanation_sv,
  engines_used,
  market_group,
  market,
  signal_rules,
  default_sl,
  default_stop_loss_pct,
  default_tp,
  default_take_profit_r,
  default_holding_time,
  default_holding_time_min,
  default_timeout_min,
  confidence_threshold = 65,
  default_timeframes,
  active = true,
  direction = 'both',
  is_new = false,
}) {
  const marketGroup = market_group || market || 'all';
  const stopLoss = default_stop_loss_pct ?? default_sl;
  const takeProfit = default_take_profit_r ?? default_tp;
  const holdingTime = default_holding_time_min ?? default_holding_time;
  const timeout = default_timeout_min ?? holdingTime;
  const description = description_sv || explanation;
  return {
    id,
    name,
    market: marketGroup,
    direction,
    description_sv: description,
    simple_explanation_sv: simple_explanation_sv || description,
    engines_used: engines_used || [],
    default_stop_loss_pct: stopLoss,
    default_take_profit_r: takeProfit,
    default_holding_time_min: holdingTime,
    default_timeout_min: timeout,
    confidence_threshold,
    paper_only: true,
    replay_enabled: true,
    batch_enabled: true,
    live_enabled: false,
    actions_allowed: false,
    can_place_orders: false,
    live_trading_enabled: false,
    safety_note_sv: 'Endast paper/replay/test. Strategin får inte lägga riktiga orders.',
    is_new,
    explanation: description,
    market_group: marketGroup,
    market_label: MARKET_LABELS[marketGroup] || marketGroup,
    signal_rules: signal_rules || engines_used || [],
    default_sl: stopLoss,
    default_tp: takeProfit,
    default_holding_time: holdingTime,
    default_timeframes,
    active,
  };
}

const STRATEGIES = Object.freeze([
  strategy({
    id: 'vwap_momentum_long',
    name: 'VWAP Momentum Long',
    explanation: 'Pris återtar VWAP med stark volym.',
    market_group: 'all',
    signal_rules: ['price_reclaims_vwap', 'volume_above_average', 'momentum_up', 'avoid_extended_entry'],
    default_sl: 0.18,
    default_tp: 1.6,
    default_holding_time: 8,
    default_timeframes: ['1m', '2m', '5m'],
    direction: 'long',
  }),
  strategy({
    id: 'vwap_rejection_short',
    name: 'VWAP Rejection Short',
    explanation: 'Pris avvisas vid VWAP och tappar styrka.',
    market_group: 'all',
    signal_rules: ['price_rejects_vwap', 'lower_high_near_vwap', 'volume_confirms_down_move', 'momentum_fades'],
    default_sl: 0.18,
    default_tp: 1.5,
    default_holding_time: 10,
    default_timeframes: ['1m', '2m', '5m'],
    direction: 'short',
  }),
  strategy({
    id: 'opening_range_breakout',
    name: 'Opening Range Breakout',
    explanation: 'Bryter över/under första 5/15/30 min range.',
    market_group: 'stocks',
    signal_rules: ['opening_range_defined', 'breaks_range_with_volume', 'holds_break_level', 'market_open_only'],
    default_sl: 0.28,
    default_tp: 1.8,
    default_holding_time: 25,
    default_timeframes: ['1m', '5m', '15m'],
  }),
  strategy({
    id: 'opening_range_fakeout',
    name: 'Opening Range Fakeout',
    explanation: 'Bryter range men faller tillbaka.',
    market_group: 'stocks',
    signal_rules: ['opening_range_defined', 'range_break_fails', 'closes_back_inside_range', 'volume_exhaustion'],
    default_sl: 0.24,
    default_tp: 1.4,
    default_holding_time: 15,
    default_timeframes: ['1m', '5m', '15m'],
  }),
  strategy({
    id: 'ema_pullback_continuation',
    name: 'EMA Pullback Continuation',
    explanation: 'Trend + rekyl mot EMA + fortsättning.',
    market_group: 'all',
    signal_rules: ['ema_trend_aligned', 'pullback_to_ema', 'continuation_candle', 'no_major_index_conflict'],
    default_sl: 0.22,
    default_tp: 1.7,
    default_holding_time: 18,
    default_timeframes: ['2m', '5m', '15m'],
  }),
  strategy({
    id: 'ema_breakdown',
    name: 'EMA Breakdown',
    explanation: 'Pris tappar EMA med volym.',
    market_group: 'all',
    signal_rules: ['price_loses_ema', 'volume_expands', 'lower_low_confirmed', 'avoid_chop'],
    default_sl: 0.22,
    default_tp: 1.5,
    default_holding_time: 14,
    default_timeframes: ['2m', '5m', '15m'],
    direction: 'short',
  }),
  strategy({
    id: 'narrow_breakout',
    name: 'Narrow Breakout',
    explanation: 'Lugnt läge följt av snabb rörelse.',
    market_group: 'all',
    signal_rules: ['narrow_state_detected', 'range_compression', 'breakout_candle', 'relative_volume_rising'],
    default_sl: 0.2,
    default_tp: 1.8,
    default_holding_time: 12,
    default_timeframes: ['1m', '2m', '5m'],
  }),
  strategy({
    id: 'volume_spike_momentum',
    name: 'Volume Spike Momentum',
    explanation: 'Ovanligt hög volym + snabb rörelse.',
    market_group: 'all',
    signal_rules: ['relative_volume_spike', 'fast_price_expansion', 'spread_not_extreme', 'follow_through_required'],
    default_sl: 0.2,
    default_tp: 1.6,
    default_holding_time: 7,
    default_timeframes: ['1m', '2m', '5m'],
  }),
  strategy({
    id: 'vwap_volume_breakout_long',
    name: 'VWAP Volume Breakout Long',
    description_sv: 'Pris bryter upp över VWAP med stark volym.',
    simple_explanation_sv: 'Systemet letar efter när priset går över en viktig nivå och många köpare kommer in samtidigt.',
    engines_used: ['VWAP-återtagning', 'Volymtopp', 'Stark rörelse'],
    market: 'all',
    direction: 'long',
    signal_rules: ['price_breaks_above_vwap', 'volume_spike', 'strong_move_up'],
    default_stop_loss_pct: 0.18,
    default_take_profit_r: 1.5,
    default_holding_time_min: 8,
    default_timeout_min: 8,
    confidence_threshold: 65,
    default_timeframes: ['1m', '2m', '5m'],
    is_new: true,
  }),
  strategy({
    id: 'vwap_failed_breakout_short',
    name: 'VWAP Failed Breakout Short',
    description_sv: 'Pris försöker bryta över VWAP men faller snabbt tillbaka.',
    simple_explanation_sv: 'Systemet letar efter falska uppgångar där priset tappar styrka.',
    engines_used: ['VWAP-avvisning', 'Volymtopp', 'Rekyl/medelvärde'],
    market: 'all',
    direction: 'short',
    signal_rules: ['vwap_breakout_fails', 'volume_spike', 'mean_reversion_down'],
    default_stop_loss_pct: 0.2,
    default_take_profit_r: 1.4,
    default_holding_time_min: 8,
    default_timeout_min: 8,
    confidence_threshold: 65,
    default_timeframes: ['1m', '2m', '5m'],
    is_new: true,
  }),
  strategy({
    id: 'narrow_state_expansion_long',
    name: 'Narrow State Expansion Long',
    description_sv: 'Lugnt och ihoptryckt pris bryter upp med stark volym.',
    simple_explanation_sv: 'Systemet väntar på att priset ska vara lugnt först och sedan röra sig starkt uppåt.',
    engines_used: ['Narrow State', 'Utbrott', 'Volymtopp', 'Stark rörelse'],
    market: 'all',
    direction: 'long',
    signal_rules: ['narrow_state_detected', 'upside_breakout', 'volume_spike', 'strong_move_up'],
    default_stop_loss_pct: 0.2,
    default_take_profit_r: 1.7,
    default_holding_time_min: 10,
    default_timeout_min: 10,
    confidence_threshold: 68,
    default_timeframes: ['1m', '2m', '5m'],
    is_new: true,
  }),
  strategy({
    id: 'narrow_state_fakeout_reversal',
    name: 'Narrow State Fakeout Reversal',
    description_sv: 'Pris bryter ut från narrow state men vänder snabbt tillbaka.',
    simple_explanation_sv: 'Systemet letar efter falska utbrott där priset lurar marknaden och sedan vänder.',
    engines_used: ['Narrow State', 'Utbrott', 'Rekyl/medelvärde'],
    market: 'all',
    direction: 'both',
    signal_rules: ['narrow_state_detected', 'breakout_fails', 'mean_reversion'],
    default_stop_loss_pct: 0.22,
    default_take_profit_r: 1.3,
    default_holding_time_min: 8,
    default_timeout_min: 8,
    confidence_threshold: 66,
    default_timeframes: ['1m', '2m', '5m'],
    is_new: true,
  }),
  strategy({
    id: 'volume_spike_continuation',
    name: 'Volume Spike Continuation',
    description_sv: 'Ovanligt hög volym följs av fortsatt rörelse i samma riktning.',
    simple_explanation_sv: 'Systemet letar efter stark volym som fortsätter driva priset.',
    engines_used: ['Volymtopp', 'Stark rörelse', 'Utbrott'],
    market: 'all',
    direction: 'both',
    signal_rules: ['volume_spike', 'strong_directional_move', 'breakout_follow_through'],
    default_stop_loss_pct: 0.18,
    default_take_profit_r: 1.5,
    default_holding_time_min: 7,
    default_timeout_min: 7,
    confidence_threshold: 65,
    default_timeframes: ['1m', '2m', '5m'],
    is_new: true,
  }),
  strategy({
    id: 'pullback_to_vwap_long',
    name: 'Pullback To VWAP Long',
    description_sv: 'Pris är i upptrend, går tillbaka till VWAP och studsar upp.',
    simple_explanation_sv: 'Systemet väntar på en liten paus i en uppgång och försöker hitta ny fortsättning upp.',
    engines_used: ['VWAP-återtagning', 'EMA-trend', 'EMA-rekyl'],
    market: 'all',
    direction: 'long',
    signal_rules: ['ema_trend_aligned', 'pullback_to_vwap', 'vwap_bounce_up'],
    default_stop_loss_pct: 0.2,
    default_take_profit_r: 1.4,
    default_holding_time_min: 10,
    default_timeout_min: 10,
    confidence_threshold: 64,
    default_timeframes: ['2m', '5m', '15m'],
    is_new: true,
  }),
  strategy({
    id: 'trend_exhaustion_short',
    name: 'Trend Exhaustion Short',
    description_sv: 'Pris har gått starkt upp men börjar tappa kraft.',
    simple_explanation_sv: 'Systemet letar efter när en uppgång börjar bli trött och kan vända ner.',
    engines_used: ['Stark rörelse', 'Rekyl/medelvärde', 'Volymtopp'],
    market: 'all',
    direction: 'short',
    signal_rules: ['strong_move_up', 'momentum_exhaustion', 'volume_spike_exhaustion'],
    default_stop_loss_pct: 0.22,
    default_take_profit_r: 1.3,
    default_holding_time_min: 8,
    default_timeout_min: 8,
    confidence_threshold: 67,
    default_timeframes: ['1m', '2m', '5m'],
    is_new: true,
  }),
  strategy({
    id: 'index_supported_momentum_long',
    name: 'Index Supported Momentum Long',
    description_sv: 'Aktie visar momentum upp samtidigt som QQQ/SPY stödjer rörelsen.',
    simple_explanation_sv: 'Systemet tar bara aktiesignaler när stora index också hjälper till.',
    engines_used: ['Stark rörelse', 'Volymtopp', 'Indexbekräftelse'],
    market: 'stocks',
    direction: 'long',
    signal_rules: ['stock_momentum_up', 'volume_spike', 'qqq_or_spy_confirms'],
    default_stop_loss_pct: 0.2,
    default_take_profit_r: 1.5,
    default_holding_time_min: 8,
    default_timeout_min: 8,
    confidence_threshold: 66,
    default_timeframes: ['1m', '2m', '5m'],
    is_new: true,
  }),
  strategy({
    id: 'crypto_fast_momentum',
    name: 'Crypto Fast Momentum',
    description_sv: 'Krypto rör sig snabbt med stark volym och kort hålltid.',
    simple_explanation_sv: 'Systemet letar efter snabba kryptorörelser och försöker stänga tidigt.',
    engines_used: ['Stark rörelse', 'Volymtopp', 'Utbrott'],
    market: 'crypto',
    direction: 'both',
    signal_rules: ['crypto_symbol', 'fast_momentum', 'volume_spike', 'breakout'],
    default_stop_loss_pct: 0.2,
    default_take_profit_r: 1.3,
    default_holding_time_min: 6,
    default_timeout_min: 6,
    confidence_threshold: 65,
    default_timeframes: ['1m', '2m', '5m'],
    is_new: true,
  }),
  strategy({
    id: 'opening_range_retest_long',
    name: 'Opening Range Retest Long',
    description_sv: 'Pris bryter opening range, testar nivån igen och fortsätter upp.',
    simple_explanation_sv: 'Systemet väntar inte bara på första utbrottet, utan även på att priset bekräftar nivån igen.',
    engines_used: ['Opening Range', 'Utbrott', 'Volymtopp', 'Stark rörelse'],
    market: 'stocks',
    direction: 'long',
    signal_rules: ['opening_range_defined', 'breaks_range_with_volume', 'retests_break_level', 'strong_move_up'],
    default_stop_loss_pct: 0.22,
    default_take_profit_r: 1.6,
    default_holding_time_min: 15,
    default_timeout_min: 15,
    confidence_threshold: 67,
    default_timeframes: ['1m', '5m', '15m'],
    is_new: true,
  }),
  strategy({
    id: 'mean_reversion_vwap',
    name: 'Mean Reversion VWAP',
    explanation: 'Överreaktion tillbaka mot VWAP.',
    market_group: 'all',
    signal_rules: ['price_extended_from_vwap', 'momentum_exhaustion', 'reversal_candle', 'target_vwap_mean'],
    default_sl: 0.25,
    default_tp: 1.3,
    default_holding_time: 16,
    default_timeframes: ['2m', '5m', '15m'],
  }),
  strategy({
    id: 'trend_continuation',
    name: 'Trend Continuation',
    explanation: 'Stark trend + paus + fortsättning.',
    market_group: 'all',
    signal_rules: ['trend_confirmed', 'pause_or_flag', 'breaks_pause_in_trend_direction', 'volume_not_weak'],
    default_sl: 0.24,
    default_tp: 1.8,
    default_holding_time: 22,
    default_timeframes: ['5m', '15m', '30m'],
  }),
  strategy({
    id: 'support_bounce',
    name: 'Support Bounce',
    explanation: 'Studs från stöd.',
    market_group: 'all',
    signal_rules: ['support_zone_identified', 'rejection_wick_or_hold', 'buyers_step_in', 'risk_defined_below_support'],
    default_sl: 0.22,
    default_tp: 1.5,
    default_holding_time: 18,
    default_timeframes: ['2m', '5m', '15m'],
    direction: 'long',
  }),
  strategy({
    id: 'resistance_rejection',
    name: 'Resistance Rejection',
    explanation: 'Avvisning från motstånd.',
    market_group: 'all',
    signal_rules: ['resistance_zone_identified', 'failed_break_or_rejection', 'sellers_step_in', 'risk_defined_above_resistance'],
    default_sl: 0.22,
    default_tp: 1.5,
    default_holding_time: 18,
    default_timeframes: ['2m', '5m', '15m'],
    direction: 'short',
  }),
  strategy({
    id: 'index_confirmed_long',
    name: 'Index Confirmed Long',
    explanation: 'Aktie long bara om QQQ/SPY stödjer.',
    market_group: 'stocks',
    signal_rules: ['stock_long_setup', 'qqq_or_spy_bullish', 'index_not_breaking_down', 'market_compass_aligned'],
    default_sl: 0.24,
    default_tp: 1.7,
    default_holding_time: 20,
    default_timeframes: ['2m', '5m', '15m'],
    direction: 'long',
  }),
  strategy({
    id: 'index_confirmed_short',
    name: 'Index Confirmed Short',
    explanation: 'Aktie short om QQQ/SPY är svag.',
    market_group: 'stocks',
    signal_rules: ['stock_short_setup', 'qqq_or_spy_bearish', 'index_not_reclaiming', 'market_compass_aligned'],
    default_sl: 0.24,
    default_tp: 1.7,
    default_holding_time: 20,
    default_timeframes: ['2m', '5m', '15m'],
    direction: 'short',
  }),
  strategy({
    id: 'crypto_momentum_scalper',
    name: 'Crypto Momentum Scalper',
    explanation: 'Krypto + stark volym + kort hålltid.',
    market_group: 'crypto',
    signal_rules: ['crypto_symbol', 'strong_relative_volume', 'fast_momentum', 'short_hold_only'],
    default_sl: 0.2,
    default_tp: 1.4,
    default_holding_time: 6,
    default_timeframes: ['1m', '2m', '5m'],
  }),
  strategy({
    id: 'low_volatility_breakout',
    name: 'Low Volatility Breakout',
    explanation: 'Låg volatilitet -> breakout.',
    market_group: 'all',
    signal_rules: ['low_volatility_regime', 'tight_range', 'range_break', 'volume_expansion'],
    default_sl: 0.18,
    default_tp: 1.9,
    default_holding_time: 16,
    default_timeframes: ['2m', '5m', '15m'],
  }),
  strategy({
    id: 'high_volatility_reversal',
    name: 'High Volatility Reversal',
    explanation: 'Hög volatilitet -> reversal.',
    market_group: 'all',
    signal_rules: ['high_volatility_regime', 'exhaustion_move', 'failed_follow_through', 'reversal_confirmation'],
    default_sl: 0.32,
    default_tp: 1.25,
    default_holding_time: 10,
    default_timeframes: ['1m', '2m', '5m'],
  }),
  strategy({
    id: 'gap_continuation',
    name: 'Gap Continuation',
    explanation: 'Gap upp/ned fortsätter.',
    market_group: 'stocks',
    signal_rules: ['opening_gap', 'gap_holds', 'volume_confirms_direction', 'no_immediate_fade'],
    default_sl: 0.3,
    default_tp: 1.7,
    default_holding_time: 30,
    default_timeframes: ['5m', '15m', '30m'],
  }),
  strategy({
    id: 'gap_fade',
    name: 'Gap Fade',
    explanation: 'Gap upp/ned fylls tillbaka.',
    market_group: 'stocks',
    signal_rules: ['opening_gap', 'failed_continuation', 'moves_back_toward_prior_close', 'volume_fade_or_reversal'],
    default_sl: 0.28,
    default_tp: 1.35,
    default_holding_time: 22,
    default_timeframes: ['2m', '5m', '15m'],
  }),
  strategy({
    id: 'news_volatility_watch',
    name: 'News Volatility Watch',
    explanation: 'Hög volatilitet efter nyhet, paper-test only.',
    market_group: 'all',
    signal_rules: ['news_or_event_volatility', 'wide_spreads_checked', 'paper_observation_only', 'no_live_execution'],
    default_sl: 0.35,
    default_tp: 1.2,
    default_holding_time: 8,
    default_timeframes: ['1m', '2m', '5m'],
    active: false,
  }),
]);

function getCatalog() {
  return {
    ok: true,
    strategies: STRATEGIES.map((s) => ({ ...s })),
    count: STRATEGIES.length,
    market_groups: Object.keys(MARKET_LABELS),
    timeframes: ['1m', '2m', '5m', '15m', '30m', '1h'],
    adjustable_parameters: [
      'stop_loss_pct',
      'take_profit_r',
      'holding_time',
      'timeout',
      'confidence_threshold',
      'volume_requirement',
      'cooldown',
      'max_trades_per_day',
      'market_group',
      'timeframe',
    ],
    ...SAFETY,
  };
}

function getStrategyById(id) {
  return STRATEGIES.find((s) => s.id === id) || null;
}

function inferStrategyForSignal(signal = {}) {
  const subtype = String(signal.signalSubtype || signal.eventType || signal.signalFamily || '').toUpperCase();
  const family = String(signal.signalFamily || '').toUpperCase();
  const state = String(signal.state || '').toUpperCase();
  const symbol = String(signal.symbol || '').toUpperCase();
  const sig = String(signal.signal || '').toUpperCase();
  const marketType = String(signal.marketType || signal.market || '').toLowerCase();

  if (marketType === 'crypto' || symbol.endsWith('USDT')) return getStrategyById('crypto_momentum_scalper');
  if (subtype.includes('VWAP_RECLAIM') || (family.includes('VWAP') && sig.includes('LONG'))) return getStrategyById('vwap_volume_breakout_long');
  if (subtype.includes('VWAP_REJECTION') || (family.includes('VWAP') && sig.includes('SHORT'))) return getStrategyById('vwap_failed_breakout_short');
  if (subtype.includes('EMA_PULLBACK')) return getStrategyById('ema_pullback_continuation');
  if (family.includes('EMA') && sig.includes('SHORT')) return getStrategyById('ema_breakdown');
  if (family.includes('NARROW') || state.includes('NARROW')) return getStrategyById('narrow_breakout');
  if (family.includes('BREAKOUT')) return getStrategyById('low_volatility_breakout');
  if (family.includes('MOMENTUM')) return getStrategyById('volume_spike_momentum');
  if (family.includes('REVERSION') || family.includes('REVERSAL')) return getStrategyById('mean_reversion_vwap');
  if (sig.includes('SHORT')) return getStrategyById('resistance_rejection');
  if (sig.includes('LONG')) return getStrategyById('support_bounce');
  return getStrategyById('trend_continuation');
}

module.exports = {
  SAFETY,
  STRATEGIES,
  getCatalog,
  getStrategyById,
  inferStrategyForSignal,
};
