'use strict';
const fs   = require('fs');
const path = require('path');

const SAFETY = Object.freeze({
  actions_allowed: false,
  can_place_orders: false,
  live_trading_enabled: false,
  agent_mode: 'config_only',
});

const PRESETS_FILE = path.resolve(__dirname, '../../data/config/strategy-presets.json');

const STRATEGY_CATALOG = [
  { key: 'vwap_reclaim',            label: 'VWAP-återtagning',         group: 'classic', scoreImpact: '+8',  desc: 'Pris återtar VWAP',                       paperOnly: false },
  { key: 'vwap_rejection',          label: 'VWAP-avvisning',           group: 'classic', scoreImpact: '+6',  desc: 'Pris avvisas vid VWAP',                   paperOnly: false },
  { key: 'ema_trend',               label: 'EMA-trend',                group: 'classic', scoreImpact: '+5',  desc: 'EMA-baserad trendföljning',               paperOnly: false },
  { key: 'ema_pullback',            label: 'EMA-rekyl',                group: 'classic', scoreImpact: '+4',  desc: 'Rekyl mot EMA i befintlig trend',         paperOnly: false },
  { key: 'narrow_state',            label: 'Narrow State',             group: 'classic', scoreImpact: '+10', desc: 'Marknaden i smalt konsolideringstillstånd', paperOnly: false },
  { key: 'breakout',                label: 'Utbrott',                  group: 'classic', scoreImpact: '+7',  desc: 'Pris bryter ut ur konsolidering',         paperOnly: false },
  { key: 'momentum',                label: 'Momentum',                 group: 'classic', scoreImpact: '+6',  desc: 'Starkt riktat prismomentum',              paperOnly: false },
  { key: 'mean_reversion',          label: 'Rekyl·Medelvärde',         group: 'classic', scoreImpact: '+4',  desc: 'Pris reverterar mot medelvärde',          paperOnly: false },
  { key: 'volume_spike',            label: 'Volymtopp',                group: 'classic', scoreImpact: '+8',  desc: 'Ovanlig volymtopp som förstärker signal', paperOnly: false },

  {
    key: 'vwap_momentum',
    label: 'VWAP Momentum',
    group: 'new',
    scoreImpact: '+10',
    holdingTime: '0–8 min',
    stopLoss: 'Tight (<0.15%)',
    volumeReq: 'Stark',
    desc: 'Pris återtar VWAP med stark volym — kort hålltid tight SL',
    explanation: 'Kärnan i systemet — VWAP + stark volym ger högst win rate',
    paperOnly: true,
  },
  {
    key: 'vwap_rejection_short',
    label: 'VWAP Rejection Short',
    group: 'new',
    scoreImpact: '+8',
    holdingTime: '0–10 min',
    stopLoss: 'Tight (<0.15%)',
    volumeReq: 'Stark',
    desc: 'Pris avvisas vid VWAP med nedåtriktning',
    explanation: 'Short-version av VWAP-setup — bearish momentum',
    paperOnly: true,
  },
  {
    key: 'opening_range_breakout',
    label: 'Opening Range Breakout',
    group: 'new',
    scoreImpact: '+12',
    holdingTime: '5–30 min',
    stopLoss: 'Medium (0.15–0.20%)',
    volumeReq: 'Hög',
    desc: 'Utbrott över/under första 5/15/30-minutersrange med volymkrav',
    explanation: 'Starkt på aktier vid öppning — kräver extra volym',
    paperOnly: true,
  },
  {
    key: 'pullback_continuation',
    label: 'Pullback Continuation',
    group: 'new',
    scoreImpact: '+8',
    holdingTime: '5–15 min',
    stopLoss: 'Medium',
    volumeReq: 'Medel',
    desc: 'Etablerad trend rekyl och återtar riktning',
    explanation: 'Trend + rekyl — bra combo med EMA-trend',
    paperOnly: true,
  },
  {
    key: 'mean_reversion_vwap',
    label: 'Mean Reversion (VWAP)',
    group: 'new',
    scoreImpact: '+6',
    holdingTime: '5–20 min',
    stopLoss: 'Medium',
    volumeReq: 'Medel',
    desc: 'Pris har rört sig långt från VWAP — söker tillbaka',
    explanation: 'Contrarian-setup — bra när trend är utmattad',
    paperOnly: true,
  },
  {
    key: 'volume_spike_momentum',
    label: 'Volume Spike Momentum',
    group: 'new',
    scoreImpact: '+10',
    holdingTime: '0–8 min',
    stopLoss: 'Tight',
    volumeReq: 'Extremt hög (3x+)',
    desc: 'Ovanligt hög volym med snabb rörelse — kort hålltid',
    explanation: 'Extremt selektiv — bara när volym är 3x+ normalt',
    paperOnly: true,
  },
  {
    key: 'index_trend_mode',
    label: 'Index Trend Mode',
    group: 'new',
    scoreImpact: '+5 om index stödjer',
    desc: 'QQQ/SPY styr — aktier får signal bara om index stödjer',
    explanation: 'TSLA bullish men QQQ svag → varning',
    paperOnly: true,
  },
  {
    key: 'sector_confirmation',
    label: 'Sector Confirmation',
    group: 'new',
    scoreImpact: '+4 om sektor stödjer',
    desc: 'Aktie får pluspoäng om sektor håller med',
    explanation: 'Extra konfidensboost från sektorn',
    paperOnly: true,
  },
  {
    key: 'news_volatility_watch',
    label: 'News/Volatility Watch',
    group: 'new',
    scoreImpact: 'Varning/kandidat',
    desc: 'Hög volatilitet ger varning eller kandidat för bevakning',
    explanation: 'Passiv — flaggar hög volatilitet utan att skapa trade',
    paperOnly: true,
  },

  // ── 15 New Research Strategies ────────────────────────────────────────────
  {
    key: 'gold_sigma',
    label: 'GoldSigma',
    group: 'research',
    scoreImpact: '+12',
    holdingTime: '5–30 min',
    stopLoss: '1%',
    targetProfit: '2%',
    volumeReq: 'Above avg',
    timeframe: '5m',
    assets: ['XAUUSD'],
    desc: 'EMA 9/39/81 pullback on Gold — long bias in bull trend',
    explanation: 'Best on longs only. Gold bull trend since 2020. +48% backtest 2020-2026. Long: close > EMA81, EMA9 > EMA39, low touches EMA9, green candle, volume > avg.',
    paperOnly: true,
  },
  {
    key: 'vol_expansion',
    label: 'VolExpansion',
    group: 'research',
    scoreImpact: '+10',
    holdingTime: '1–4 hours',
    stopLoss: '5%',
    targetProfit: '8%',
    volumeReq: 'ATR > 1.5x avg',
    timeframe: '1H',
    assets: ['BTCUSD', 'SOLUSD', 'XRPUSD', 'AVAXUSD'],
    desc: 'Bollinger Band squeeze then expansion + EMA trend + RSI filter',
    explanation: '+17.9% backtest, 572 trades. BB squeeze → expand. Long: close > EMA20 > EMA50 + RSI 52-75 + ATR > 1.5x avg.',
    paperOnly: true,
  },
  {
    key: 'mean_reversion_us30',
    label: 'MeanReversion US30',
    group: 'research',
    scoreImpact: '+8',
    holdingTime: '15–60 min',
    stopLoss: '1%',
    targetProfit: '1.5%',
    volumeReq: 'Normal',
    timeframe: '15m',
    assets: ['US30'],
    desc: 'Price deviates from VWAP then returns — RSI confirmation',
    explanation: '+11% backtest. Contrarian setup on US30. Long: Price below VWAP + RSI oversold + candle reversal.',
    paperOnly: true,
  },
  {
    key: 'gold_swing',
    label: 'GoldSwing',
    group: 'research',
    scoreImpact: '+9',
    holdingTime: '5–30 min',
    stopLoss: '1.5%',
    targetProfit: '3%',
    volumeReq: 'OK',
    timeframe: '5m',
    assets: ['XAUUSD'],
    desc: 'EMA pullback in trend — wider parameters than GoldSigma',
    explanation: '+10-40% backtest depending on version. Swing version of GoldSigma with wider stops.',
    paperOnly: true,
  },
  {
    key: 'iron_scalper',
    label: 'IronScalper',
    group: 'research',
    scoreImpact: '+7',
    holdingTime: '2–10 min',
    stopLoss: '0.5%',
    targetProfit: '1%',
    volumeReq: 'Spike required',
    timeframe: '5m',
    assets: ['BTCUSD', 'ETHUSD', 'XAUUSD', 'NAS100'],
    desc: 'EMA alignment + RSI 40-60 + volume spike combined scalp',
    explanation: '+2-15% backtest. Works on any asset with volume. Long: EMA bullish + RSI 40-60 + volume spike.',
    paperOnly: true,
  },
  {
    key: 'rsi_divergence',
    label: 'RSI Divergence',
    group: 'research',
    scoreImpact: '+11',
    holdingTime: '1–4 hours',
    stopLoss: '1.5%',
    targetProfit: '3%',
    volumeReq: 'Normal',
    timeframe: '1H',
    assets: ['BTCUSD', 'ETHUSD', 'XAUUSD', 'EURUSD', 'NAS100'],
    desc: 'Price makes new high/low but RSI does not — divergence signal',
    explanation: 'Expected 60-65% win rate. Bullish: price new low + RSI higher low. Bearish: price new high + RSI lower high.',
    paperOnly: true,
  },
  {
    key: 'vwap_momentum_v2',
    label: 'VWAP Momentum v2',
    group: 'research',
    scoreImpact: '+10',
    holdingTime: '5–15 min',
    stopLoss: '0.15%',
    targetProfit: '1.5%',
    volumeReq: '2x avg required',
    timeframe: '5m',
    assets: ['BTCUSD', 'ETHUSD', 'SPY', 'QQQ', 'XAUUSD'],
    desc: 'Price reclaims or rejects VWAP with volume spike 2x+',
    explanation: 'Upgraded VWAP setup with strict volume filter. Long: crosses above VWAP + volume > 2x avg + green candle.',
    paperOnly: true,
  },
  {
    key: 'orb_session',
    label: 'Opening Range Breakout (Session)',
    group: 'research',
    scoreImpact: '+12',
    holdingTime: '10–30 min',
    stopLoss: '0.2%',
    targetProfit: '0.5%',
    volumeReq: 'High',
    timeframe: '5m',
    assets: ['SPY', 'QQQ', 'AAPL', 'TSLA', 'NVDA', 'BTCUSD'],
    desc: 'Break of first 30min high/low — London 08:00 UTC / NY 13:30 UTC',
    explanation: 'Session-aware ORB. Strong at market open with volume spike. Long: close above 30min high + volume spike.',
    paperOnly: true,
  },
  {
    key: 'bb_squeeze',
    label: 'Bollinger Band Squeeze',
    group: 'research',
    scoreImpact: '+9',
    holdingTime: '15–60 min',
    stopLoss: '1%',
    targetProfit: '2%',
    volumeReq: 'Above avg',
    timeframe: '15m',
    assets: ['BTCUSD', 'ETHUSD', 'XAUUSD', 'SPY', 'QQQ'],
    desc: 'BB width narrows then expands — breakout with volume',
    explanation: 'Squeeze → expansion is one of the most reliable setups. Long: candle closes above upper BB after squeeze + volume.',
    paperOnly: true,
  },
  {
    key: 'supertrend',
    label: 'Supertrend',
    group: 'research',
    scoreImpact: '+8',
    holdingTime: '1–4 hours',
    stopLoss: 'ATR-based',
    targetProfit: '3%',
    volumeReq: 'Normal',
    timeframe: '1H',
    assets: ['BTCUSD', 'ETHUSD', 'XAUUSD', 'NAS100', 'US500'],
    desc: 'Supertrend flips direction — ATR multiplier 3.0, period 10',
    explanation: 'Simple and effective on trending assets. Green = long, Red = short.',
    paperOnly: true,
  },
  {
    key: 'macd_volume',
    label: 'MACD + Volume',
    group: 'research',
    scoreImpact: '+9',
    holdingTime: '1–4 hours',
    stopLoss: '1%',
    targetProfit: '2.5%',
    volumeReq: '> 20-bar avg',
    timeframe: '1H',
    assets: ['BTCUSD', 'ETHUSD', 'SOLUSD', 'BNBUSD'],
    desc: 'MACD histogram crosses zero with volume confirmation',
    explanation: 'Classic MACD with volume filter. Long: MACD crosses above signal + volume > 20-bar avg.',
    paperOnly: true,
  },
  {
    key: 'sr_break',
    label: 'Support/Resistance Break',
    group: 'research',
    scoreImpact: '+10',
    holdingTime: '15–60 min',
    stopLoss: '1%',
    targetProfit: '2%',
    volumeReq: '1.5x avg',
    timeframe: '15m',
    assets: ['BTCUSD', 'ETHUSD', 'XAUUSD', 'SPY', 'QQQ', 'NAS100'],
    desc: 'Key level break with strong candle + volume 1.5x+',
    explanation: 'S/R breaks with volume are high probability setups. Long: close above resistance + volume > 1.5x avg.',
    paperOnly: true,
  },
  {
    key: 'fvg',
    label: 'Fair Value Gap (FVG)',
    group: 'research',
    scoreImpact: '+11',
    holdingTime: '15–60 min',
    stopLoss: '1%',
    targetProfit: '2%',
    volumeReq: 'Normal',
    timeframe: '15m',
    assets: ['BTCUSD', 'ETHUSD', 'NAS100', 'US500', 'US30'],
    desc: 'Price fills institutional imbalance zone — FVG retracement',
    explanation: 'Price fills gaps left by institutional orders. Bullish FVG forms + price retraces to fill it.',
    paperOnly: true,
  },
  {
    key: 'smc',
    label: 'Smart Money Concepts',
    group: 'research',
    scoreImpact: '+11',
    holdingTime: '1–4 hours',
    stopLoss: '1.5%',
    targetProfit: '3%',
    volumeReq: 'Normal',
    timeframe: '1H',
    assets: ['BTCUSD', 'ETHUSD', 'XAUUSD', 'NAS100', 'EURUSD', 'GBPUSD'],
    desc: 'Break of structure + order block retest',
    explanation: 'BOS + order block = high probability institutional setup. Long: bullish BOS + price retests bullish order block.',
    paperOnly: true,
  },
  {
    key: 'ema_pullback_v2',
    label: 'EMA Pullback Continuation v2',
    group: 'research',
    scoreImpact: '+9',
    holdingTime: '5–30 min',
    stopLoss: '0.5%',
    targetProfit: '1.5%',
    volumeReq: 'Normal',
    timeframe: '5m',
    assets: ['BTCUSD', 'ETHUSD', 'SPY', 'QQQ', 'XAUUSD', 'EURUSD'],
    desc: 'EMA9 > EMA21 > EMA50 — pullback to EMA9 and bounce',
    explanation: 'Triple EMA alignment is strongest trend filter. Long: EMA9 > EMA21 > EMA50, price pulls to EMA9, bounces, green candle.',
    paperOnly: true,
  },
];

const BUILT_IN_PRESETS = [
  {
    id: 'vwap_scalper',
    name: 'VWAP Scalper',
    icon: '⚡',
    description: 'VWAP + volym kort hålltid tight SL',
    toggles: { vwap_reclaim: true, vwap_rejection: true, volume_spike: true, vwap_momentum: true, narrow_state: false, ema_trend: false, ema_pullback: false },
    params: { stop_loss: 0.12, holding_time: 8, timeout: 8, confidence_threshold: 65 },
    exits: { trailing_stop: true, profit_target: true, time_exit: false },
    blockerMode: 'tight',
  },
  {
    id: 'index_stocks',
    name: 'Index-confirmed Stocks',
    icon: '📈',
    description: 'Aktier + index som filter',
    toggles: { vwap_reclaim: true, narrow_state: true, index_trend_mode: true, sector_confirmation: true, ai_agent: true },
    params: { confidence_threshold: 65, holding_time: 15 },
    exits: { profit_target: true, trailing_stop: true },
    blockerMode: 'tight',
  },
  {
    id: 'crypto_momentum',
    name: 'Crypto Momentum',
    icon: '₿',
    description: 'Krypto med momentumfokus',
    toggles: { vwap_reclaim: true, momentum: true, volume_spike: true, volume_spike_momentum: true, narrow_state: true },
    params: { stop_loss: 0.15, holding_time: 10, confidence_threshold: 60 },
    exits: { trailing_stop: true, profit_target: true },
    blockerMode: 'medium',
  },
  {
    id: 'loose_discovery',
    name: 'Loose Discovery',
    icon: '🔬',
    description: 'Fler signaler — samla mer data',
    toggles: { vwap_reclaim: true, vwap_rejection: true, narrow_state: true, breakout: true, momentum: true, volume_spike: true, vwap_momentum: true, opening_range_breakout: true },
    params: { confidence_threshold: 40, holding_time: 15 },
    exits: { profit_target: true, trailing_stop: true, time_exit: true },
    blockerMode: 'loose',
    discoveryMode: true,
  },
  {
    id: 'tight_scalp',
    name: 'Tight Risk Scalping',
    icon: '🎯',
    description: 'Maximal skydd — bara bästa signalerna',
    toggles: { vwap_reclaim: true, narrow_state: true, vwap_momentum: true, volume_spike: true, ai_agent: true, risk_engine: true, safety_engine: true },
    params: { stop_loss: 0.10, holding_time: 5, confidence_threshold: 75, timeout: 5 },
    exits: { trailing_stop: true, profit_target: true, time_exit: false },
    blockerMode: 'tight',
  },
  {
    id: 'opening_range_test',
    name: 'Opening Range Test',
    icon: '🔔',
    description: 'Opening Range Breakout aktier vid öppning',
    toggles: { opening_range_breakout: true, volume_spike: true, breakout: true },
    params: { confidence_threshold: 60, holding_time: 20 },
    exits: { profit_target: true, trailing_stop: true },
    blockerMode: 'medium',
  },
  {
    id: 'gold_research',
    name: 'Gold Research',
    icon: '🥇',
    description: 'GoldSigma + GoldSwing — research on XAUUSD',
    toggles: { gold_sigma: true, gold_swing: true, rsi_divergence: true },
    params: { confidence_threshold: 65, holding_time: 20 },
    exits: { profit_target: true, trailing_stop: true },
    blockerMode: 'medium',
  },
  {
    id: 'crypto_research',
    name: 'Crypto Research',
    icon: '🔬',
    description: 'VolExpansion + MACD + BB Squeeze on crypto',
    toggles: { vol_expansion: true, macd_volume: true, bb_squeeze: true, rsi_divergence: true },
    params: { confidence_threshold: 60, holding_time: 60 },
    exits: { profit_target: true, trailing_stop: true },
    blockerMode: 'medium',
  },
  {
    id: 'smart_money',
    name: 'Smart Money',
    icon: '🏦',
    description: 'SMC + FVG + RSI Divergence',
    toggles: { smc: true, fvg: true, rsi_divergence: true, sr_break: true },
    params: { confidence_threshold: 70, holding_time: 120 },
    exits: { profit_target: true, trailing_stop: true },
    blockerMode: 'tight',
  },
];

function loadCustomPresets() {
  try {
    const raw = fs.readFileSync(PRESETS_FILE, 'utf8');
    return JSON.parse(raw);
  } catch (_) {
    return [];
  }
}

function savePresetsFile(presets) {
  fs.mkdirSync(path.dirname(PRESETS_FILE), { recursive: true });
  fs.writeFileSync(PRESETS_FILE, JSON.stringify(presets, null, 2), 'utf8');
}

function getCatalog() {
  return {
    strategies: STRATEGY_CATALOG,
    newStrategies: STRATEGY_CATALOG.filter(s => s.group === 'new'),
    classicStrategies: STRATEGY_CATALOG.filter(s => s.group === 'classic'),
    researchStrategies: STRATEGY_CATALOG.filter(s => s.group === 'research'),
    ...SAFETY,
  };
}

function getPresets() {
  return {
    builtIn: BUILT_IN_PRESETS,
    custom: loadCustomPresets(),
    ...SAFETY,
  };
}

function saveCustomPreset(preset) {
  const presets = loadCustomPresets();
  const idx = presets.findIndex(p => p.id === preset.id);
  if (idx !== -1) {
    presets[idx] = preset;
  } else {
    presets.push(preset);
  }
  savePresetsFile(presets);
  return { ok: true, preset, ...SAFETY };
}

function deleteCustomPreset(id) {
  const presets = loadCustomPresets().filter(p => p.id !== id);
  savePresetsFile(presets);
  return { ok: true, ...SAFETY };
}

module.exports = {
  SAFETY,
  STRATEGY_CATALOG,
  BUILT_IN_PRESETS,
  getCatalog,
  getPresets,
  saveCustomPreset,
  deleteCustomPreset,
};