export {
  UNAVAILABLE,
  WAITING_RUNTIME,
  collectMatchingFields,
  compactJsonValue,
  exposedFieldRows,
  field,
  firstPathValue,
  hasAnyFieldValue,
  isPlainObject,
  moneyText,
  numericTone,
  percentText,
  primitiveEntries,
  sourcePayload,
  timeText,
  unwrapSources,
  valueAt,
  valueText,
} from '../../domain/DomainUtils.js';
